### ISSUE TITLE
Add web socket support in the backend

### ISSUE THREAD

**Issue by tomaspalma** [NIAEFEUP/tts-be#89]
There two discussed options in [this issue](https://github.com/NIAEFEUP/tts-fe/issues/165):

- [Django channels](https://github.com/django/channels)
- [Python socketio](https://pypi.org/project/python-socketio/)

**Comment by Process-ing** [comment]
I will be using [Python Socket.IO](https://pypi.org/project/python-socketio/), see [this comment](https://github.com/NIAEFEUP/tts-fe/issues/165#issuecomment-2296675305), for the discussion
